### ISSUE TITLE
Can't build on GNU/Linux

### ISSUE THREAD

**Issue by vanfanel** [fabzzap/libaudiotap#1]
Hi,

I am on an x86_64 machine and I get this:

manuel@vader:~/src/libaudiotap$ make libaudiotap.so
cc    -c -o libaudiotap.o libaudiotap.c
cc    -c -o libaudiotap_external_symbols.o libaudiotap_external_symbols.c
cc    -c -o pthread_wait_event.o pthread_wait_event.c
cc -shared -o libaudiotap.so libaudiotap.o libaudiotap_external_symbols.o pthread_wait_event.o -ldl 
/usr/bin/ld: libaudiotap.o: relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
libaudiotap.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
Makefile:14: recipe for target 'libaudiotap.so' failed
make: *** [libaudiotap.so] Error 1

GCC version is 5.3.1

I tried to build the objects with -fPIC and then link manually, with no success... any ideas?

**Comment by fabzzap** [comment]
Have you tried adding `LINUX64BIT=1` to the command line? That recommendation has been added to the README file as well
